services:
  api:
    # Substitua pelo URI do seu repositório ECR do backend
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY_BACKEND}:latest
    container_name: assistente-gpt-backend
    restart: always
    ports:
      - "8000:8000"
    # Variáveis de ambiente
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      # No EC2 simples, o front está no mesmo IP público
      - FRONTEND_URL=${FRONTEND_URL}
  web:
    # Substitua pelo URI do seu repositório ECR do frontend
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY_FRONTEND}:latest
    container_name: assistente-gpt-frontend
    environment:
      - VITE_API_URL=${VITE_API_URL}
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api