services:
  api:
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY_BACKEND}:latest
    container_name: assistente-gpt-backend
    restart: always
    ports:
      - "8000:8000"
    # Vari√°veis de ambiente
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - FRONTEND_URL=${FRONTEND_URL}
  web:
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY_FRONTEND}:latest
    container_name: assistente-gpt-frontend
    environment:
      - VITE_API_URL=${VITE_API_URL}
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api